name: GitHub Pages Publish
on:
  workflow_dispatch: {}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          source_dir: docs/
          asciidoctor_params: "--require asciidoctor-diagram --attribute=sectlinks --attribute=sectanchors"
