name: GitHub Pages Publish
on:
  workflow_dispatch: {}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: asciidoctor-ghpages
        uses: k-wall/asciidoctor-ghpages-action@2937242409c0c8c0db639bde63ed1528bad067c8
        with:
          source_dir: docs/
          asciidoctor_params: "--require asciidoctor-diagram --attribute=sectlinks --attribute=sectanchors"
